# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  test-go:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

  transpile:
    runs-on: ubuntu-latest
    steps:
    - name: OpenAI Commit
      uses: riccardolinares/openai-commit@v0.0.1
      with:
        openai-api-key: test
        openai-prompt: test
        model: text-davinci-003

  test-py:
    runs-on: ubuntu-latest
    steps:
    - name: Run pytest
    # You may pin to the exact commit or the version.
    # uses: pavelzw/pytest-action@c9e5b9c8d93290ff47dcf6a28c6b19ca0b42e487
      uses: pavelzw/pytest-action@v2.1.0
      # with:
      #   # Print a GitHub job summary
      #   job-summary: true # optional, default is true
      #   # Verbose output
      #   verbose: true # optional, default is true
      #   # Use emojis in the output
      #   emoji: true # optional, default is true
      #   # Custom arguments to pass to pytest
      #   custom-arguments: "" # optional, default is 
      #   # Custom command to replace the `pytest` call. Can be a custom executable or something like `poetry run pytest` or `micromamba run -n myenv pytest`.
      #   custom-pytest: "pytest" # optional, default is pytest
      #   # Title of the report
      #   report-title: Test Report # optional, default is Test Report
      #   # Add 'Click to expand' to the report
      #   click-to-expand: true # optional, default is true

  upload-pypi-test:
    runs-on: ubuntu-latest
    steps:
      - name: pypi-publish
      # You may pin to the exact commit or the version.
      # uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc
        uses: pypa/gh-action-pypi-publish@v1.12.4
        # with:
          # PyPI user
          # user: # optional, default is __token__
          # # Password for your PyPI user or an access token
          # password: # optional
          # # The repository URL to use
          # repository-url: # optional
          # # [DEPRECATED] The repository URL to use
          # repository_url: # optional, default is https://upload.pypi.org/legacy/
          # # The target directory for distribution
          # packages-dir: # optional
          # # [DEPRECATED] The target directory for distribution
          # packages_dir: # optional, default is dist
          # # Check metadata before uploading
          # verify-metadata: # optional
          # # [DEPRECATED] Check metadata before uploading
          # verify_metadata: # optional, default is true
          # # Do not fail if a Python package distribution exists in the target package index
          # skip-existing: # optional
          # # [DEPRECATED] Do not fail if a Python package distribution exists in the target package index
          # skip_existing: # optional, default is false
          # # Show verbose output.
          # verbose: # optional, default is false
          # # Show hash values of files to be uploaded
          # print-hash: # optional
          # # [DEPRECATED] Show hash values of files to be uploaded
          # print_hash: # optional, default is false
          # # [EXPERIMENTAL] Enable experimental support for PEP 740 attestations. Only works with PyPI and TestPyPI via Trusted Publishing.
          # attestations: # optional, default is true
          
          
    
